### ISSUE TITLE
ImageJ - Color image brightness/contrast unintended resetting

### ISSUE THREAD

**Issue by johnsinsheimer** [areaDetector/ADViewers#1]
This may be more of an ImageJ issue than ADViewer (EPICS_AD_Viewer.java) but currently if settings in ImageJ, such as brightness or contrast are changed, the next image acquired by the ADViewer plugin resets the brightness and contrast to some default value.  This issue happens with RGB1 color mode, but not the Mono color mode.

Mark Rivers also verified this behavior with EPICS_NTNDA_Viewer.java.

**Comment by MarkRivers** [comment]
This behavior is fixed in R1-5.
