### ISSUE TITLE
Support for compressed NTNDArrays in EPICS_NTNDA_Viewer.java

### ISSUE THREAD

**Issue by MarkRivers** [areaDetector/ADViewers#3]
ADCore R3-4 adds support for compressing NDArrays in NDPluginCodec, and serving compressed NTNDArrays in NDPluginPva.

The ImageJ EPICS_NTNDA_Viewer.java code needs to support reading such compressed arrays, since it can substantially reduce network traffic when the areaDetector IOC and ImageJ viewer are running on different machines.

**Comment by MarkRivers** [comment]
I now have a beta implementation of this in the "decompress" branch of ADViewers.  

It requires the master branch of ADSupport (soon to be R1-6).

The RELEASE.md file in this repository explains what needs to be done to enable this plugin to handle decompressed arrays.  This involves making the jpeg and blosc shareable libraries accessible from ImageJ, since is uses Java JNA to use the native C decompressors.

All of the integer data types work with all blosc compression options.  JPEG decompression is working with UInt8 arrays, which is the only type that NDPluginCodec currently supports.

The only thing that is not yet working is blosc decompression for Float32 and Float64 arrays.  I need help hopefully from @brunoseivam to understand and fix this.

**Comment by MarkRivers** [comment]
@brunoseivam has fixed the code in ADCore so that compressed NTNDArrays are always data type UInt8. The codec.parameters encodes the actual data type.

The ImageJ plugin has been changed to work with these changes.  It now works correctly with all data types, including Float32 and Float64.

**Comment by brunoseivam** [comment]
@shroffk would this be useful for a potential CS-Studio implementation, too? :raised_hands:

**Comment by MarkRivers** [comment]
This issue is resolved, compressed arrays are now supported.
